version: "v2.0"
name: "测试构建并推送镜像"
label: []
stages:
- name: "stage-3"
  label:
  - "Build"
  jobs:
    job_dE4:
      name: "构建环境-LINUX"
      steps:
      - checkout: self
        with:
          enableGitLfs: false
      - name: "创建目录"
        run: |-
          mkdir -p test
          ls ./src/
          cat ./src/Dockerfile
      - name: "Docker构建镜像和镜像复制转存"
        uses: "DockerBuildPushGo@1.*"
        with:
          selectOp: "login_build_push"
          sourceMirrorTicketPair: "[{\"id\":\"dockerLoginParam\",\"values\":[{\"id\"\
            :\"RepoHost\",\"value\":\"\"},{\"id\":\"LDCredentialId\",\"value\":\"\"\
            }]}]"
          targetAuthType: "MY_INPUT"
          targetRegUsername: "${{ settings.mirrors_token.username }}"
          targetRegPassword: "${{ settings.mirrors_token.password }}"
          targetImage: "mirrors.tencent.com/randy-test/test1"
          targetImageName: ""
          targetImageTag: "newfortest"
          dockerBuildDir: "./src"
          dockerFilePath: "./src/Dockerfile"
          dockerBuildArgs: ""
          prootIgnorePath: |-
            /etc/hosts
            /etc/resolv.conf
            /etc/nsswitch.conf
          targetRepoItemStr: []
          sourceRepoItemsStr: []
      - run: |
          sleep 1000
